#!/bin/sh
set -e

echo "Downloading $pkg..."
wget https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.56.0.tar.gz

echo "Extracting FastFetch..."
tar -xf "fastfetch-2.56.0.tar.gz"
cd "fastfetch-2.56.0" || exit 1

echo "Changing Dir to build..."
mkdir -p build
cd build

echo "Cmake..."
cmake .. -DCMAKE_BUILD_TYPE=Release
cmake --build .
