#!/bin/sh
set -e

SOURCE_DIR="nano-8.6"

cd "$SOURCE_DIR"

echo "./configure..."
./configure --prefix=/usr      \
            --sysconfdir=/etc  \
            --enable-utf8      \
            --docdir=/usr/share/doc/nano-8.6 &&
echo "Making Nano..."
make

echo "Installing..."
make install &&
install -v -m644 doc/{nano.html,sample.nanorc} "$DESTDIR"/usr/share/doc/nano-8.6
